//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK__Almacen__ID_Prod__182C9B23", "Productos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataInventarioCDGC.Productos), "Almacen", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Almacen), true)]
[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK__Ventas__ID_Clien__117F9D94", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Clientes), "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataInventarioCDGC.Ventas), true)]
[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK__Ventas__ID_Produ__1273C1CD", "Productos", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Productos), "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataInventarioCDGC.Ventas), true)]
[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK__Usuarios__ID_Rol__0CBAE877", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Roles), "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataInventarioCDGC.Usuarios), true)]
[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK__Ventas__ID_Usuar__1367E606", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Usuarios), "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataInventarioCDGC.Ventas), true)]

#endregion

namespace DataInventarioCDGC
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InventarioCDGCEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InventarioCDGCEntities object using the connection string found in the 'InventarioCDGCEntities' section of the application configuration file.
        /// </summary>
        public InventarioCDGCEntities() : base("name=InventarioCDGCEntities", "InventarioCDGCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InventarioCDGCEntities object.
        /// </summary>
        public InventarioCDGCEntities(string connectionString) : base(connectionString, "InventarioCDGCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InventarioCDGCEntities object.
        /// </summary>
        public InventarioCDGCEntities(EntityConnection connection) : base(connection, "InventarioCDGCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Almacen> Almacen
        {
            get
            {
                if ((_Almacen == null))
                {
                    _Almacen = base.CreateObjectSet<Almacen>("Almacen");
                }
                return _Almacen;
            }
        }
        private ObjectSet<Almacen> _Almacen;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Productos> Productos
        {
            get
            {
                if ((_Productos == null))
                {
                    _Productos = base.CreateObjectSet<Productos>("Productos");
                }
                return _Productos;
            }
        }
        private ObjectSet<Productos> _Productos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Roles> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Roles>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Roles> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ventas> Ventas
        {
            get
            {
                if ((_Ventas == null))
                {
                    _Ventas = base.CreateObjectSet<Ventas>("Ventas");
                }
                return _Ventas;
            }
        }
        private ObjectSet<Ventas> _Ventas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Almacen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlmacen(Almacen almacen)
        {
            base.AddObject("Almacen", almacen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Productos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductos(Productos productos)
        {
            base.AddObject("Productos", productos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Roles roles)
        {
            base.AddObject("Roles", roles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ventas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVentas(Ventas ventas)
        {
            base.AddObject("Ventas", ventas);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Almacen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Almacen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Almacen object.
        /// </summary>
        /// <param name="iD_Producto">Initial value of the ID_Producto property.</param>
        public static Almacen CreateAlmacen(global::System.Int32 iD_Producto)
        {
            Almacen almacen = new Almacen();
            almacen.ID_Producto = iD_Producto;
            return almacen;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                if (_ID_Producto != value)
                {
                    OnID_ProductoChanging(value);
                    ReportPropertyChanging("ID_Producto");
                    _ID_Producto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Producto");
                    OnID_ProductoChanged();
                }
            }
        }
        private global::System.Int32 _ID_Producto;
        partial void OnID_ProductoChanging(global::System.Int32 value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Existencia
        {
            get
            {
                return _Existencia;
            }
            set
            {
                OnExistenciaChanging(value);
                ReportPropertyChanging("Existencia");
                _Existencia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Existencia");
                OnExistenciaChanged();
            }
        }
        private Nullable<global::System.Int32> _Existencia;
        partial void OnExistenciaChanging(Nullable<global::System.Int32> value);
        partial void OnExistenciaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Almacen__ID_Prod__182C9B23", "Productos")]
        public Productos Productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Productos>("InventarioCDGCModel.FK__Almacen__ID_Prod__182C9B23", "Productos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Productos>("InventarioCDGCModel.FK__Almacen__ID_Prod__182C9B23", "Productos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Productos> ProductosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Productos>("InventarioCDGCModel.FK__Almacen__ID_Prod__182C9B23", "Productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Productos>("InventarioCDGCModel.FK__Almacen__ID_Prod__182C9B23", "Productos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clientes object.
        /// </summary>
        /// <param name="iD_Cliente">Initial value of the ID_Cliente property.</param>
        public static Clientes CreateClientes(global::System.Int32 iD_Cliente)
        {
            Clientes clientes = new Clientes();
            clientes.ID_Cliente = iD_Cliente;
            return clientes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Cliente
        {
            get
            {
                return _ID_Cliente;
            }
            set
            {
                if (_ID_Cliente != value)
                {
                    OnID_ClienteChanging(value);
                    ReportPropertyChanging("ID_Cliente");
                    _ID_Cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Cliente");
                    OnID_ClienteChanged();
                }
            }
        }
        private global::System.Int32 _ID_Cliente;
        partial void OnID_ClienteChanging(global::System.Int32 value);
        partial void OnID_ClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                OnCedulaChanging(value);
                ReportPropertyChanging("Cedula");
                _Cedula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cedula");
                OnCedulaChanged();
            }
        }
        private global::System.String _Cedula;
        partial void OnCedulaChanging(global::System.String value);
        partial void OnCedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Clien__117F9D94", "Ventas")]
        public EntityCollection<Ventas> Ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ventas>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ventas>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Ventas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Productos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Productos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Productos object.
        /// </summary>
        /// <param name="iD_Producto">Initial value of the ID_Producto property.</param>
        public static Productos CreateProductos(global::System.Int32 iD_Producto)
        {
            Productos productos = new Productos();
            productos.ID_Producto = iD_Producto;
            return productos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                if (_ID_Producto != value)
                {
                    OnID_ProductoChanging(value);
                    ReportPropertyChanging("ID_Producto");
                    _ID_Producto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Producto");
                    OnID_ProductoChanged();
                }
            }
        }
        private global::System.Int32 _ID_Producto;
        partial void OnID_ProductoChanging(global::System.Int32 value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Producto
        {
            get
            {
                return _Producto;
            }
            set
            {
                OnProductoChanging(value);
                ReportPropertyChanging("Producto");
                _Producto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Producto");
                OnProductoChanged();
            }
        }
        private global::System.String _Producto;
        partial void OnProductoChanging(global::System.String value);
        partial void OnProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio_Venta
        {
            get
            {
                return _Precio_Venta;
            }
            set
            {
                OnPrecio_VentaChanging(value);
                ReportPropertyChanging("Precio_Venta");
                _Precio_Venta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio_Venta");
                OnPrecio_VentaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio_Venta;
        partial void OnPrecio_VentaChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecio_VentaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Almacen__ID_Prod__182C9B23", "Almacen")]
        public Almacen Almacen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Almacen>("InventarioCDGCModel.FK__Almacen__ID_Prod__182C9B23", "Almacen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Almacen>("InventarioCDGCModel.FK__Almacen__ID_Prod__182C9B23", "Almacen").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Almacen> AlmacenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Almacen>("InventarioCDGCModel.FK__Almacen__ID_Prod__182C9B23", "Almacen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Almacen>("InventarioCDGCModel.FK__Almacen__ID_Prod__182C9B23", "Almacen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Produ__1273C1CD", "Ventas")]
        public EntityCollection<Ventas> Ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ventas>("InventarioCDGCModel.FK__Ventas__ID_Produ__1273C1CD", "Ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ventas>("InventarioCDGCModel.FK__Ventas__ID_Produ__1273C1CD", "Ventas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Roles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Roles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Roles object.
        /// </summary>
        /// <param name="iD_Rol">Initial value of the ID_Rol property.</param>
        public static Roles CreateRoles(global::System.Int32 iD_Rol)
        {
            Roles roles = new Roles();
            roles.ID_Rol = iD_Rol;
            return roles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Rol
        {
            get
            {
                return _ID_Rol;
            }
            set
            {
                if (_ID_Rol != value)
                {
                    OnID_RolChanging(value);
                    ReportPropertyChanging("ID_Rol");
                    _ID_Rol = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Rol");
                    OnID_RolChanged();
                }
            }
        }
        private global::System.Int32 _ID_Rol;
        partial void OnID_RolChanging(global::System.Int32 value);
        partial void OnID_RolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rol
        {
            get
            {
                return _Rol;
            }
            set
            {
                OnRolChanging(value);
                ReportPropertyChanging("Rol");
                _Rol = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rol");
                OnRolChanged();
            }
        }
        private global::System.String _Rol;
        partial void OnRolChanging(global::System.String value);
        partial void OnRolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Permisos
        {
            get
            {
                return _Permisos;
            }
            set
            {
                OnPermisosChanging(value);
                ReportPropertyChanging("Permisos");
                _Permisos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Permisos");
                OnPermisosChanged();
            }
        }
        private Nullable<global::System.Int32> _Permisos;
        partial void OnPermisosChanging(Nullable<global::System.Int32> value);
        partial void OnPermisosChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Usuarios__ID_Rol__0CBAE877", "Usuarios")]
        public EntityCollection<Usuarios> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuarios>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuarios>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuarios object.
        /// </summary>
        /// <param name="iD_Usuario">Initial value of the ID_Usuario property.</param>
        public static Usuarios CreateUsuarios(global::System.Int32 iD_Usuario)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.ID_Usuario = iD_Usuario;
            return usuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Usuario
        {
            get
            {
                return _ID_Usuario;
            }
            set
            {
                if (_ID_Usuario != value)
                {
                    OnID_UsuarioChanging(value);
                    ReportPropertyChanging("ID_Usuario");
                    _ID_Usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Usuario");
                    OnID_UsuarioChanged();
                }
            }
        }
        private global::System.Int32 _ID_Usuario;
        partial void OnID_UsuarioChanging(global::System.Int32 value);
        partial void OnID_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Rol
        {
            get
            {
                return _ID_Rol;
            }
            set
            {
                OnID_RolChanging(value);
                ReportPropertyChanging("ID_Rol");
                _ID_Rol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Rol");
                OnID_RolChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Rol;
        partial void OnID_RolChanging(Nullable<global::System.Int32> value);
        partial void OnID_RolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contrasena
        {
            get
            {
                return _Contrasena;
            }
            set
            {
                OnContrasenaChanging(value);
                ReportPropertyChanging("Contrasena");
                _Contrasena = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contrasena");
                OnContrasenaChanged();
            }
        }
        private global::System.String _Contrasena;
        partial void OnContrasenaChanging(global::System.String value);
        partial void OnContrasenaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Usuarios__ID_Rol__0CBAE877", "Roles")]
        public Roles Roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roles>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roles>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Roles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Roles> RolesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roles>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Roles>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Roles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Usuar__1367E606", "Ventas")]
        public EntityCollection<Ventas> Ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ventas>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ventas>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Ventas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Ventas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ventas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ventas object.
        /// </summary>
        /// <param name="iD_Venta">Initial value of the ID_Venta property.</param>
        public static Ventas CreateVentas(global::System.Int32 iD_Venta)
        {
            Ventas ventas = new Ventas();
            ventas.ID_Venta = iD_Venta;
            return ventas;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Venta
        {
            get
            {
                return _ID_Venta;
            }
            set
            {
                if (_ID_Venta != value)
                {
                    OnID_VentaChanging(value);
                    ReportPropertyChanging("ID_Venta");
                    _ID_Venta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Venta");
                    OnID_VentaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Venta;
        partial void OnID_VentaChanging(global::System.Int32 value);
        partial void OnID_VentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Cliente
        {
            get
            {
                return _ID_Cliente;
            }
            set
            {
                OnID_ClienteChanging(value);
                ReportPropertyChanging("ID_Cliente");
                _ID_Cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Cliente");
                OnID_ClienteChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Cliente;
        partial void OnID_ClienteChanging(Nullable<global::System.Int32> value);
        partial void OnID_ClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                OnID_ProductoChanging(value);
                ReportPropertyChanging("ID_Producto");
                _ID_Producto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Producto");
                OnID_ProductoChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Producto;
        partial void OnID_ProductoChanging(Nullable<global::System.Int32> value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Usuario
        {
            get
            {
                return _ID_Usuario;
            }
            set
            {
                OnID_UsuarioChanging(value);
                ReportPropertyChanging("ID_Usuario");
                _ID_Usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Usuario");
                OnID_UsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Usuario;
        partial void OnID_UsuarioChanging(Nullable<global::System.Int32> value);
        partial void OnID_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio_Unidad
        {
            get
            {
                return _Precio_Unidad;
            }
            set
            {
                OnPrecio_UnidadChanging(value);
                ReportPropertyChanging("Precio_Unidad");
                _Precio_Unidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio_Unidad");
                OnPrecio_UnidadChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio_Unidad;
        partial void OnPrecio_UnidadChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecio_UnidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private Nullable<global::System.Int32> _Cantidad;
        partial void OnCantidadChanging(Nullable<global::System.Int32> value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Descuento
        {
            get
            {
                return _Descuento;
            }
            set
            {
                OnDescuentoChanging(value);
                ReportPropertyChanging("Descuento");
                _Descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Descuento");
                OnDescuentoChanged();
            }
        }
        private Nullable<global::System.Decimal> _Descuento;
        partial void OnDescuentoChanging(Nullable<global::System.Decimal> value);
        partial void OnDescuentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacion
        {
            get
            {
                return _Observacion;
            }
            set
            {
                OnObservacionChanging(value);
                ReportPropertyChanging("Observacion");
                _Observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacion");
                OnObservacionChanged();
            }
        }
        private global::System.String _Observacion;
        partial void OnObservacionChanging(global::System.String value);
        partial void OnObservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Clien__117F9D94", "Clientes")]
        public Clientes Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clientes> ClientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clientes>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Produ__1273C1CD", "Productos")]
        public Productos Productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Productos>("InventarioCDGCModel.FK__Ventas__ID_Produ__1273C1CD", "Productos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Productos>("InventarioCDGCModel.FK__Ventas__ID_Produ__1273C1CD", "Productos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Productos> ProductosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Productos>("InventarioCDGCModel.FK__Ventas__ID_Produ__1273C1CD", "Productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Productos>("InventarioCDGCModel.FK__Ventas__ID_Produ__1273C1CD", "Productos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Usuar__1367E606", "Usuarios")]
        public Usuarios Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuarios> UsuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuarios>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuarios>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Usuarios", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
