//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK__Ventas__ID_Clien__117F9D94", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Cliente), "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataInventarioCDGC.Venta), true)]
[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK__Usuarios__ID_Rol__0CBAE877", "Roles", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Role), "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataInventarioCDGC.Usuario), true)]
[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK__Ventas__ID_Usuar__1367E606", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Usuario), "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataInventarioCDGC.Venta), true)]
[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK_VentaDetalle_Ventas", "Ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Venta), "VentaDetalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataInventarioCDGC.VentaDetalle), true)]
[assembly: EdmRelationshipAttribute("InventarioCDGCModel", "FK_VentaDetalle_Almacen", "Almacen", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataInventarioCDGC.Almacen), "VentaDetalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataInventarioCDGC.VentaDetalle), true)]

#endregion

namespace DataInventarioCDGC
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InventarioCDGCEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InventarioCDGCEntities1 object using the connection string found in the 'InventarioCDGCEntities1' section of the application configuration file.
        /// </summary>
        public InventarioCDGCEntities1() : base("name=InventarioCDGCEntities1", "InventarioCDGCEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InventarioCDGCEntities1 object.
        /// </summary>
        public InventarioCDGCEntities1(string connectionString) : base(connectionString, "InventarioCDGCEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InventarioCDGCEntities1 object.
        /// </summary>
        public InventarioCDGCEntities1(EntityConnection connection) : base(connection, "InventarioCDGCEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Almacen> Almacens
        {
            get
            {
                if ((_Almacens == null))
                {
                    _Almacens = base.CreateObjectSet<Almacen>("Almacens");
                }
                return _Almacens;
            }
        }
        private ObjectSet<Almacen> _Almacens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Producto> Productos
        {
            get
            {
                if ((_Productos == null))
                {
                    _Productos = base.CreateObjectSet<Producto>("Productos");
                }
                return _Productos;
            }
        }
        private ObjectSet<Producto> _Productos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VentaDetalle> VentaDetalles
        {
            get
            {
                if ((_VentaDetalles == null))
                {
                    _VentaDetalles = base.CreateObjectSet<VentaDetalle>("VentaDetalles");
                }
                return _VentaDetalles;
            }
        }
        private ObjectSet<VentaDetalle> _VentaDetalles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Venta> Ventas
        {
            get
            {
                if ((_Ventas == null))
                {
                    _Ventas = base.CreateObjectSet<Venta>("Ventas");
                }
                return _Ventas;
            }
        }
        private ObjectSet<Venta> _Ventas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_Productos> vw_Productos
        {
            get
            {
                if ((_vw_Productos == null))
                {
                    _vw_Productos = base.CreateObjectSet<vw_Productos>("vw_Productos");
                }
                return _vw_Productos;
            }
        }
        private ObjectSet<vw_Productos> _vw_Productos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwFactura> vwFacturas
        {
            get
            {
                if ((_vwFacturas == null))
                {
                    _vwFacturas = base.CreateObjectSet<vwFactura>("vwFacturas");
                }
                return _vwFacturas;
            }
        }
        private ObjectSet<vwFactura> _vwFacturas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwVenta> vwVentas
        {
            get
            {
                if ((_vwVentas == null))
                {
                    _vwVentas = base.CreateObjectSet<vwVenta>("vwVentas");
                }
                return _vwVentas;
            }
        }
        private ObjectSet<vwVenta> _vwVentas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Almacens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlmacens(Almacen almacen)
        {
            base.AddObject("Almacens", almacen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Productos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductos(Producto producto)
        {
            base.AddObject("Productos", producto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VentaDetalles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVentaDetalles(VentaDetalle ventaDetalle)
        {
            base.AddObject("VentaDetalles", ventaDetalle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ventas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVentas(Venta venta)
        {
            base.AddObject("Ventas", venta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vw_Productos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_Productos(vw_Productos vw_Productos)
        {
            base.AddObject("vw_Productos", vw_Productos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwFacturas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwFacturas(vwFactura vwFactura)
        {
            base.AddObject("vwFacturas", vwFactura);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwVentas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwVentas(vwVenta vwVenta)
        {
            base.AddObject("vwVentas", vwVenta);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Almacen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Almacen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Almacen object.
        /// </summary>
        /// <param name="iD_Producto">Initial value of the ID_Producto property.</param>
        public static Almacen CreateAlmacen(global::System.String iD_Producto)
        {
            Almacen almacen = new Almacen();
            almacen.ID_Producto = iD_Producto;
            return almacen;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                if (_ID_Producto != value)
                {
                    OnID_ProductoChanging(value);
                    ReportPropertyChanging("ID_Producto");
                    _ID_Producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Producto");
                    OnID_ProductoChanged();
                }
            }
        }
        private global::System.String _ID_Producto;
        partial void OnID_ProductoChanging(global::System.String value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Existencia
        {
            get
            {
                return _Existencia;
            }
            set
            {
                OnExistenciaChanging(value);
                ReportPropertyChanging("Existencia");
                _Existencia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Existencia");
                OnExistenciaChanged();
            }
        }
        private Nullable<global::System.Int32> _Existencia;
        partial void OnExistenciaChanging(Nullable<global::System.Int32> value);
        partial void OnExistenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Producto_1
        {
            get
            {
                return _Producto_1;
            }
            set
            {
                OnProducto_1Changing(value);
                ReportPropertyChanging("Producto_1");
                _Producto_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Producto_1");
                OnProducto_1Changed();
            }
        }
        private global::System.String _Producto_1;
        partial void OnProducto_1Changing(global::System.String value);
        partial void OnProducto_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio_Venta
        {
            get
            {
                return _Precio_Venta;
            }
            set
            {
                OnPrecio_VentaChanging(value);
                ReportPropertyChanging("Precio_Venta");
                _Precio_Venta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio_Venta");
                OnPrecio_VentaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio_Venta;
        partial void OnPrecio_VentaChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecio_VentaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK_VentaDetalle_Almacen", "VentaDetalle")]
        public EntityCollection<VentaDetalle> VentaDetalles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VentaDetalle>("InventarioCDGCModel.FK_VentaDetalle_Almacen", "VentaDetalle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VentaDetalle>("InventarioCDGCModel.FK_VentaDetalle_Almacen", "VentaDetalle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="iD_Cliente">Initial value of the ID_Cliente property.</param>
        public static Cliente CreateCliente(global::System.Int32 iD_Cliente)
        {
            Cliente cliente = new Cliente();
            cliente.ID_Cliente = iD_Cliente;
            return cliente;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Cliente
        {
            get
            {
                return _ID_Cliente;
            }
            set
            {
                if (_ID_Cliente != value)
                {
                    OnID_ClienteChanging(value);
                    ReportPropertyChanging("ID_Cliente");
                    _ID_Cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Cliente");
                    OnID_ClienteChanged();
                }
            }
        }
        private global::System.Int32 _ID_Cliente;
        partial void OnID_ClienteChanging(global::System.Int32 value);
        partial void OnID_ClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                OnCedulaChanging(value);
                ReportPropertyChanging("Cedula");
                _Cedula = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cedula");
                OnCedulaChanged();
            }
        }
        private global::System.String _Cedula;
        partial void OnCedulaChanging(global::System.String value);
        partial void OnCedulaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RNC
        {
            get
            {
                return _RNC;
            }
            set
            {
                OnRNCChanging(value);
                ReportPropertyChanging("RNC");
                _RNC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RNC");
                OnRNCChanged();
            }
        }
        private global::System.String _RNC;
        partial void OnRNCChanging(global::System.String value);
        partial void OnRNCChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Clien__117F9D94", "Ventas")]
        public EntityCollection<Venta> Ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Ventas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Producto object.
        /// </summary>
        /// <param name="iD_Producto">Initial value of the ID_Producto property.</param>
        public static Producto CreateProducto(global::System.String iD_Producto)
        {
            Producto producto = new Producto();
            producto.ID_Producto = iD_Producto;
            return producto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                if (_ID_Producto != value)
                {
                    OnID_ProductoChanging(value);
                    ReportPropertyChanging("ID_Producto");
                    _ID_Producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Producto");
                    OnID_ProductoChanged();
                }
            }
        }
        private global::System.String _ID_Producto;
        partial void OnID_ProductoChanging(global::System.String value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Producto1
        {
            get
            {
                return _Producto1;
            }
            set
            {
                OnProducto1Changing(value);
                ReportPropertyChanging("Producto1");
                _Producto1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Producto1");
                OnProducto1Changed();
            }
        }
        private global::System.String _Producto1;
        partial void OnProducto1Changing(global::System.String value);
        partial void OnProducto1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio_Venta
        {
            get
            {
                return _Precio_Venta;
            }
            set
            {
                OnPrecio_VentaChanging(value);
                ReportPropertyChanging("Precio_Venta");
                _Precio_Venta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio_Venta");
                OnPrecio_VentaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio_Venta;
        partial void OnPrecio_VentaChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecio_VentaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="iD_Rol">Initial value of the ID_Rol property.</param>
        public static Role CreateRole(global::System.Int32 iD_Rol)
        {
            Role role = new Role();
            role.ID_Rol = iD_Rol;
            return role;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Rol
        {
            get
            {
                return _ID_Rol;
            }
            set
            {
                if (_ID_Rol != value)
                {
                    OnID_RolChanging(value);
                    ReportPropertyChanging("ID_Rol");
                    _ID_Rol = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Rol");
                    OnID_RolChanged();
                }
            }
        }
        private global::System.Int32 _ID_Rol;
        partial void OnID_RolChanging(global::System.Int32 value);
        partial void OnID_RolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rol
        {
            get
            {
                return _Rol;
            }
            set
            {
                OnRolChanging(value);
                ReportPropertyChanging("Rol");
                _Rol = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rol");
                OnRolChanged();
            }
        }
        private global::System.String _Rol;
        partial void OnRolChanging(global::System.String value);
        partial void OnRolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Permisos
        {
            get
            {
                return _Permisos;
            }
            set
            {
                OnPermisosChanging(value);
                ReportPropertyChanging("Permisos");
                _Permisos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Permisos");
                OnPermisosChanged();
            }
        }
        private Nullable<global::System.Int32> _Permisos;
        partial void OnPermisosChanging(Nullable<global::System.Int32> value);
        partial void OnPermisosChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Usuarios__ID_Rol__0CBAE877", "Usuarios")]
        public EntityCollection<Usuario> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="iD_Usuario">Initial value of the ID_Usuario property.</param>
        public static Usuario CreateUsuario(global::System.Int32 iD_Usuario)
        {
            Usuario usuario = new Usuario();
            usuario.ID_Usuario = iD_Usuario;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Usuario
        {
            get
            {
                return _ID_Usuario;
            }
            set
            {
                if (_ID_Usuario != value)
                {
                    OnID_UsuarioChanging(value);
                    ReportPropertyChanging("ID_Usuario");
                    _ID_Usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Usuario");
                    OnID_UsuarioChanged();
                }
            }
        }
        private global::System.Int32 _ID_Usuario;
        partial void OnID_UsuarioChanging(global::System.Int32 value);
        partial void OnID_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Rol
        {
            get
            {
                return _ID_Rol;
            }
            set
            {
                OnID_RolChanging(value);
                ReportPropertyChanging("ID_Rol");
                _ID_Rol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Rol");
                OnID_RolChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Rol;
        partial void OnID_RolChanging(Nullable<global::System.Int32> value);
        partial void OnID_RolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contrasena
        {
            get
            {
                return _Contrasena;
            }
            set
            {
                OnContrasenaChanging(value);
                ReportPropertyChanging("Contrasena");
                _Contrasena = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contrasena");
                OnContrasenaChanged();
            }
        }
        private global::System.String _Contrasena;
        partial void OnContrasenaChanging(global::System.String value);
        partial void OnContrasenaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Usuarios__ID_Rol__0CBAE877", "Roles")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Roles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Roles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("InventarioCDGCModel.FK__Usuarios__ID_Rol__0CBAE877", "Roles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Usuar__1367E606", "Ventas")]
        public EntityCollection<Venta> Ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Ventas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="Venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Venta object.
        /// </summary>
        /// <param name="iD_Venta">Initial value of the ID_Venta property.</param>
        public static Venta CreateVenta(global::System.Int32 iD_Venta)
        {
            Venta venta = new Venta();
            venta.ID_Venta = iD_Venta;
            return venta;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Venta
        {
            get
            {
                return _ID_Venta;
            }
            set
            {
                if (_ID_Venta != value)
                {
                    OnID_VentaChanging(value);
                    ReportPropertyChanging("ID_Venta");
                    _ID_Venta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Venta");
                    OnID_VentaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Venta;
        partial void OnID_VentaChanging(global::System.Int32 value);
        partial void OnID_VentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Cliente
        {
            get
            {
                return _ID_Cliente;
            }
            set
            {
                OnID_ClienteChanging(value);
                ReportPropertyChanging("ID_Cliente");
                _ID_Cliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Cliente");
                OnID_ClienteChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Cliente;
        partial void OnID_ClienteChanging(Nullable<global::System.Int32> value);
        partial void OnID_ClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Usuario
        {
            get
            {
                return _ID_Usuario;
            }
            set
            {
                OnID_UsuarioChanging(value);
                ReportPropertyChanging("ID_Usuario");
                _ID_Usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Usuario");
                OnID_UsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Usuario;
        partial void OnID_UsuarioChanging(Nullable<global::System.Int32> value);
        partial void OnID_UsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacion
        {
            get
            {
                return _Observacion;
            }
            set
            {
                OnObservacionChanging(value);
                ReportPropertyChanging("Observacion");
                _Observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacion");
                OnObservacionChanged();
            }
        }
        private global::System.String _Observacion;
        partial void OnObservacionChanging(global::System.String value);
        partial void OnObservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Clien__117F9D94", "Clientes")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("InventarioCDGCModel.FK__Ventas__ID_Clien__117F9D94", "Clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK__Ventas__ID_Usuar__1367E606", "Usuarios")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("InventarioCDGCModel.FK__Ventas__ID_Usuar__1367E606", "Usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK_VentaDetalle_Ventas", "VentaDetalle")]
        public EntityCollection<VentaDetalle> VentaDetalles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VentaDetalle>("InventarioCDGCModel.FK_VentaDetalle_Ventas", "VentaDetalle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VentaDetalle>("InventarioCDGCModel.FK_VentaDetalle_Ventas", "VentaDetalle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="VentaDetalle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VentaDetalle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VentaDetalle object.
        /// </summary>
        /// <param name="iD_Detalle">Initial value of the ID_Detalle property.</param>
        public static VentaDetalle CreateVentaDetalle(global::System.Int32 iD_Detalle)
        {
            VentaDetalle ventaDetalle = new VentaDetalle();
            ventaDetalle.ID_Detalle = iD_Detalle;
            return ventaDetalle;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Detalle
        {
            get
            {
                return _ID_Detalle;
            }
            set
            {
                if (_ID_Detalle != value)
                {
                    OnID_DetalleChanging(value);
                    ReportPropertyChanging("ID_Detalle");
                    _ID_Detalle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Detalle");
                    OnID_DetalleChanged();
                }
            }
        }
        private global::System.Int32 _ID_Detalle;
        partial void OnID_DetalleChanging(global::System.Int32 value);
        partial void OnID_DetalleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_Venta
        {
            get
            {
                return _ID_Venta;
            }
            set
            {
                OnID_VentaChanging(value);
                ReportPropertyChanging("ID_Venta");
                _ID_Venta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Venta");
                OnID_VentaChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_Venta;
        partial void OnID_VentaChanging(Nullable<global::System.Int32> value);
        partial void OnID_VentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                OnID_ProductoChanging(value);
                ReportPropertyChanging("ID_Producto");
                _ID_Producto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ID_Producto");
                OnID_ProductoChanged();
            }
        }
        private global::System.String _ID_Producto;
        partial void OnID_ProductoChanging(global::System.String value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio_Unidad
        {
            get
            {
                return _Precio_Unidad;
            }
            set
            {
                OnPrecio_UnidadChanging(value);
                ReportPropertyChanging("Precio_Unidad");
                _Precio_Unidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio_Unidad");
                OnPrecio_UnidadChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio_Unidad;
        partial void OnPrecio_UnidadChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecio_UnidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private Nullable<global::System.Int32> _Cantidad;
        partial void OnCantidadChanging(Nullable<global::System.Int32> value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Descuento
        {
            get
            {
                return _Descuento;
            }
            set
            {
                OnDescuentoChanging(value);
                ReportPropertyChanging("Descuento");
                _Descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Descuento");
                OnDescuentoChanged();
            }
        }
        private Nullable<global::System.Decimal> _Descuento;
        partial void OnDescuentoChanging(Nullable<global::System.Decimal> value);
        partial void OnDescuentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _Total;
        partial void OnTotalChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK_VentaDetalle_Ventas", "Ventas")]
        public Venta Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("InventarioCDGCModel.FK_VentaDetalle_Ventas", "Ventas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("InventarioCDGCModel.FK_VentaDetalle_Ventas", "Ventas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Venta> VentaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("InventarioCDGCModel.FK_VentaDetalle_Ventas", "Ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Venta>("InventarioCDGCModel.FK_VentaDetalle_Ventas", "Ventas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InventarioCDGCModel", "FK_VentaDetalle_Almacen", "Almacen")]
        public Almacen Almacen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Almacen>("InventarioCDGCModel.FK_VentaDetalle_Almacen", "Almacen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Almacen>("InventarioCDGCModel.FK_VentaDetalle_Almacen", "Almacen").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Almacen> AlmacenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Almacen>("InventarioCDGCModel.FK_VentaDetalle_Almacen", "Almacen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Almacen>("InventarioCDGCModel.FK_VentaDetalle_Almacen", "Almacen", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="vw_Productos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_Productos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vw_Productos object.
        /// </summary>
        /// <param name="iD_Producto">Initial value of the ID_Producto property.</param>
        public static vw_Productos Createvw_Productos(global::System.String iD_Producto)
        {
            vw_Productos vw_Productos = new vw_Productos();
            vw_Productos.ID_Producto = iD_Producto;
            return vw_Productos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                if (_ID_Producto != value)
                {
                    OnID_ProductoChanging(value);
                    ReportPropertyChanging("ID_Producto");
                    _ID_Producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Producto");
                    OnID_ProductoChanged();
                }
            }
        }
        private global::System.String _ID_Producto;
        partial void OnID_ProductoChanging(global::System.String value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Producto
        {
            get
            {
                return _Producto;
            }
            set
            {
                OnProductoChanging(value);
                ReportPropertyChanging("Producto");
                _Producto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Producto");
                OnProductoChanged();
            }
        }
        private global::System.String _Producto;
        partial void OnProductoChanging(global::System.String value);
        partial void OnProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio_Venta
        {
            get
            {
                return _Precio_Venta;
            }
            set
            {
                OnPrecio_VentaChanging(value);
                ReportPropertyChanging("Precio_Venta");
                _Precio_Venta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio_Venta");
                OnPrecio_VentaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio_Venta;
        partial void OnPrecio_VentaChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecio_VentaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="vwFactura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwFactura : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwFactura object.
        /// </summary>
        /// <param name="iD_Venta">Initial value of the ID_Venta property.</param>
        /// <param name="iD_Detalle">Initial value of the ID_Detalle property.</param>
        public static vwFactura CreatevwFactura(global::System.Int32 iD_Venta, global::System.Int32 iD_Detalle)
        {
            vwFactura vwFactura = new vwFactura();
            vwFactura.ID_Venta = iD_Venta;
            vwFactura.ID_Detalle = iD_Detalle;
            return vwFactura;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Venta
        {
            get
            {
                return _ID_Venta;
            }
            set
            {
                OnID_VentaChanging(value);
                ReportPropertyChanging("ID_Venta");
                _ID_Venta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_Venta");
                OnID_VentaChanged();
            }
        }
        private global::System.Int32 _ID_Venta;
        partial void OnID_VentaChanging(global::System.Int32 value);
        partial void OnID_VentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacion
        {
            get
            {
                return _Observacion;
            }
            set
            {
                OnObservacionChanging(value);
                ReportPropertyChanging("Observacion");
                _Observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacion");
                OnObservacionChanged();
            }
        }
        private global::System.String _Observacion;
        partial void OnObservacionChanging(global::System.String value);
        partial void OnObservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cliente
        {
            get
            {
                return _Cliente;
            }
            set
            {
                OnClienteChanging(value);
                ReportPropertyChanging("Cliente");
                _Cliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cliente");
                OnClienteChanged();
            }
        }
        private global::System.String _Cliente;
        partial void OnClienteChanging(global::System.String value);
        partial void OnClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Producto
        {
            get
            {
                return _Producto;
            }
            set
            {
                OnProductoChanging(value);
                ReportPropertyChanging("Producto");
                _Producto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Producto");
                OnProductoChanged();
            }
        }
        private global::System.String _Producto;
        partial void OnProductoChanging(global::System.String value);
        partial void OnProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Precio_Unidad
        {
            get
            {
                return _Precio_Unidad;
            }
            set
            {
                OnPrecio_UnidadChanging(value);
                ReportPropertyChanging("Precio_Unidad");
                _Precio_Unidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio_Unidad");
                OnPrecio_UnidadChanged();
            }
        }
        private Nullable<global::System.Decimal> _Precio_Unidad;
        partial void OnPrecio_UnidadChanging(Nullable<global::System.Decimal> value);
        partial void OnPrecio_UnidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private Nullable<global::System.Int32> _Cantidad;
        partial void OnCantidadChanging(Nullable<global::System.Int32> value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Descuento
        {
            get
            {
                return _Descuento;
            }
            set
            {
                OnDescuentoChanging(value);
                ReportPropertyChanging("Descuento");
                _Descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Descuento");
                OnDescuentoChanged();
            }
        }
        private Nullable<global::System.Decimal> _Descuento;
        partial void OnDescuentoChanging(Nullable<global::System.Decimal> value);
        partial void OnDescuentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _Total;
        partial void OnTotalChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Detalle
        {
            get
            {
                return _ID_Detalle;
            }
            set
            {
                if (_ID_Detalle != value)
                {
                    OnID_DetalleChanging(value);
                    ReportPropertyChanging("ID_Detalle");
                    _ID_Detalle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Detalle");
                    OnID_DetalleChanged();
                }
            }
        }
        private global::System.Int32 _ID_Detalle;
        partial void OnID_DetalleChanging(global::System.Int32 value);
        partial void OnID_DetalleChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InventarioCDGCModel", Name="vwVenta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwVenta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwVenta object.
        /// </summary>
        /// <param name="iD_Venta">Initial value of the ID_Venta property.</param>
        public static vwVenta CreatevwVenta(global::System.Int32 iD_Venta)
        {
            vwVenta vwVenta = new vwVenta();
            vwVenta.ID_Venta = iD_Venta;
            return vwVenta;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Venta
        {
            get
            {
                return _ID_Venta;
            }
            set
            {
                if (_ID_Venta != value)
                {
                    OnID_VentaChanging(value);
                    ReportPropertyChanging("ID_Venta");
                    _ID_Venta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Venta");
                    OnID_VentaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Venta;
        partial void OnID_VentaChanging(global::System.Int32 value);
        partial void OnID_VentaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cliente
        {
            get
            {
                return _Cliente;
            }
            set
            {
                OnClienteChanging(value);
                ReportPropertyChanging("Cliente");
                _Cliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cliente");
                OnClienteChanged();
            }
        }
        private global::System.String _Cliente;
        partial void OnClienteChanging(global::System.String value);
        partial void OnClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _Total;
        partial void OnTotalChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vendedor
        {
            get
            {
                return _Vendedor;
            }
            set
            {
                OnVendedorChanging(value);
                ReportPropertyChanging("Vendedor");
                _Vendedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vendedor");
                OnVendedorChanged();
            }
        }
        private global::System.String _Vendedor;
        partial void OnVendedorChanging(global::System.String value);
        partial void OnVendedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacion
        {
            get
            {
                return _Observacion;
            }
            set
            {
                OnObservacionChanging(value);
                ReportPropertyChanging("Observacion");
                _Observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacion");
                OnObservacionChanged();
            }
        }
        private global::System.String _Observacion;
        partial void OnObservacionChanging(global::System.String value);
        partial void OnObservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();

        #endregion

    
    }

    #endregion

    
}
